apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  selector:
    app: go-web-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP 